# -*- coding: utf-8 -*-
"""PSNR Video

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nfdjsl33xCcQIi0_bG2I4sEEhYITWgBL
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage.measure import compare_psnr
import cv2

ref_img = cv2.imread('/content/webrtc 6 client sumber 1.jpg')
noisy_img = cv2.imread('/content/6 client (client) 1.jpg')
 
PSNR = compare_psnr(ref_img,noisy_img)
print(PSNR)

