# -*- coding: utf-8 -*-
"""PSNR audio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGUSxXbirwO6jAlESHHgxJ-GdqbFRO59
"""

from scipy.io import wavfile

from math import log10, sqrt 
import cv2 
import numpy as np 
  
def PSNR(original, noise):
    mse = np.mean((original - noise) ** 2) 
    if(mse == 0):  # MSE is zero means no noise is present in the signal . 
                  # Therefore PSNR have no importance. 
        return 100
    max_db = 65536
    psnr = 20 * log10(max_db / sqrt(mse)) 
    return psnr

originalsample, original = wavfile.read('/content/6clientsumber.wav')
noisesample, noise = wavfile.read('/content/6clientpenerima.wav')
value = PSNR(original, noise) 
print(f"PSNR value is {value} dB")
